ALTER TABLE projects ADD COLUMN IF NOT EXISTS start_date DATE;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS total_area NUMERIC;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS number_of_floors INTEGER;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS floor_areas JSONB;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS rate_per_sqft NUMERIC;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS extra_works JSONB;

ALTER TABLE expenses ADD COLUMN IF NOT EXISTS location TEXT;

ALTER TABLE income ADD COLUMN IF NOT EXISTS location TEXT;

